name: Build entity database
on:
  schedule:
  - cron: 0 4 * * *
  workflow_dispatch:
env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_S3_SECRET_ACCESS_KEY}}
        aws-region: eu-west-2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Setup git
      run: 'git config user.email "${DLB_BOT_EMAIL}"

        git config user.name "${DLB_BOT_USERNAME}"

        git remote set-url origin https://${DLB_BOT_USERNAME}:${DLB_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

        git checkout ${GITHUB_REF##*/}

        '
    - name: Submit build job on AWS Batch
      run:  make aws-build
